### PR TITLE
Treat clone failures as warnings and continue to attempt to

### LINKED ISSUE #7: Should handle existing repository gracefully
Currently if you attempt to clone a repository into an existing directory careen will fail as follows:

```
rodin:careen-davidewatson dwat$ go build && ./careen-davidewatson clone
INFO: Using careen config file: /Users/dwat/workspace/careen-davidewatson/config.yaml
INFO: Cloning packages from manifest ./manifests/docker.yaml
INFO: Cloning package docker from https://github.com/docker/docker.git to ./src/docker
█▒▒▒▒▒▒▒▒▒ ERROR: './src/docker' exists and is not an empty directory
ERROR: Failed to clone repo https://github.com/docker/docker.git to destination ./src/docker
rodin:careen-davidewatson dwat$ 
```

Instead careen should check if the directory contains the correct repository, checkout the master branch, update it if necessary, and checkout the requested tag.

### PR DESCRIPTION
**Pull request by davidewatson**
checkout the tag (Fixes #7) Also ensure the spinner stops before
any output is printed.

### CODE REVIEW

File: cmd/clone.go [hunk 1]
```diff
@@ -75,20 +77,18 @@ var cloneCmd = &cobra.Command{
 		for _, pkg := range manifest.Packages {
 			repoDir := outputDir + pkg.Name
 			fmt.Printf("INFO: Cloning package %v from %v to %v\n", pkg.Name, pkg.Repo, repoDir)
-			terminalSpinner.Start()
 			err = Clone(pkg.Repo, pkg.Revision, repoDir)
 			if err != nil {
-				fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
-				ExitCode = 1
-				return
+				fmt.Fprintf(os.Stderr, "WARNING: %v\n", err)
```
Comment (coffeepac) [inline cmd/clone.go]: could we re structure this to check if the target folder has the desired repo in it before a clone attempt?  then we eject on errors here.

Comment (davidewatson) [inline cmd/clone.go]: CheckoutByTag(), which is called after Clone(), is necessary to do this because it is not enough to find that you have a repo (which GitOpenRepository() does). You actually have to have a repo which contains the requested tag (which is what GitCheckoutByTag() does). Part of the reason this code is structured as it is is that I wanted to isolate all git2go code from the command code.

I think however, that having a warning is wrong, cf. https://dave.cheney.net/2015/11/05/lets-talk-about-logging, so I agree with your general sentiment, even if for different reasons.

I will ponder this weekend, but honestly think this is probably the best approach.

Comment (davidewatson) [inline cmd/clone.go]: I suppose we could create CloneByTag() to avoid the warning, but would be weird nomenclature for git. Essentially the warning is just info. Clone() can fail here and it might be all good.

**Comment by davidewatson** [comment]
I've added an IsEmpty() function and avoid calling Clone() if we know it will fail. After we have working docker builds I would like to migrate apply to use git2go.

**Comment by coffeepac** [comment]
@davidewatson not exactly what I was thinking.  I was thinking to test the directory for a. existence and b. does it have the correct git repo, so an invocation of 'git remote -v' or somesuch.  But parsing git remote -v would be gnarly.

this is all temporary code and should be getting executing inside of a docker container where it is a known and controlled environment, this is fine.

**Comment by coffeepac** [comment]
LGTM  merge whenever you're ready for it.

**Comment by davidewatson** [comment]
Ack.
